"""Draft the next PCOS_NOW from the worklist, a RECON parse and the previous PCOS_NOW."""
from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

from . import __version__
from .common import (
    ACTIVE_LOW_STATUS,
    ACTIVE_STATUSES,
    PERSONAL_ROOM,
    STALE_STATUS,
    WAITING_STATUS,
    WorklistError,
    age_days,
    fence_flags,
    get_vocab,
    md_table,
    normalize_title,
    parse_date,
    read_text_file,
    read_worklist,
    room_sort_key,
    unescape_md,
)
from .recon_parse import load_recon, split_people

DRAFT_NAME = "PCOS_NOW_draft.md"
# Section 0 (JOE TODAY) is carried through when present and never created.
SECTION_NAMES = {
    1: "DECISIONS",
    2: "ACTIVE",
    3: "WAITING ON OTHERS",
    4: "DELTAS",
    5: "CANDIDATES",
    6: "STALE BLOCK",
    7: "POINTERS AND ROOM SOURCE MAPS",
    8: "SYSTEM STATUS",
}
DEFAULT_HEADINGS = {number: f"## {number}. {name}" for number, name in SECTION_NAMES.items()}
# Sections are located by the leading number only; the title text is free.
# A heading is "## N", "## N.", "## N)", "## N.TITLE", "## N - title" (1 to 6
# hashes, at least one space after them) or, in files without such headings,
# "**N. title**". A number followed by another digit ("## 10", "## 2.1",
# "## 2026-08-25") is not a section, and nothing inside a code fence is.
# A Google Docs Markdown export escapes the punctuation ("# 0\\. Joe today");
# the optional backslash before it is accepted.
HASH_NUMBERED_RE = re.compile(r"^\s{0,3}#{1,6}[ \t]+(\d)(?:\\?[.):\-](?!\d)|(?=\s|$))\s*(.*?)\s*#*\s*$")
BOLD_NUMBERED_RE = re.compile(r"^\s{0,3}\*\*\s*(\d)(?:\\?[.):\-](?!\d)|(?=[\s*]|$))\s*(.*?)\s*\*\*\s*$")
NUMBERED_ITEM_RE = re.compile(r"^\s*(\d+)[.)]\s+")
GENERATOR_MARK = "<!-- PCOS_NOW draft generated by pcos_tools"
# The v3 PCOS_NOW (Sep 2026) is hand-written narrative: section 2 "Current work
# and stopping points", 3 "Dependencies", 6 "Stale matters". Regenerating those
# from the Worklist would delete the narrative, so a file with any of these
# titles is carried unchanged and checked with now_check instead.
NARRATIVE_TITLES = {2: ("current work",), 3: ("dependenc",), 6: ("stale matters",)}


# -------------------------------------------------------- previous PCOS_NOW --

def parse_now(text):
    """Split a PCOS_NOW markdown into a preamble and numbered sections 0..8.

    Returns {"preamble": [...], "sections": {n: {...}}, "style": "hash"|"bold"}.
    Lines inside fenced code blocks are never headings.
    """
    lines = text.splitlines()
    fenced = fence_flags(lines)
    heading_mode = any(not in_fence and HASH_NUMBERED_RE.match(line) for line, in_fence in zip(lines, fenced))
    sections, preamble, current, level = {}, [], None, None
    for line, in_fence in zip(lines, fenced):
        match = None
        if not in_fence:
            match = HASH_NUMBERED_RE.match(line) or (None if heading_mode else BOLD_NUMBERED_RE.match(line))
        if match and heading_mode:
            # Sections all sit at the level of the first numbered heading, so a
            # sub-heading such as "## 7 vendors to call" inside "# 2." is body text.
            hashes = len(line.lstrip()) - len(line.lstrip().lstrip("#"))
            if level is None:
                level = hashes
            elif hashes != level:
                match = None
        if match:
            number = int(match.group(1))
            if 0 <= number <= 8 and number not in sections:
                sections[number] = {"heading": line.rstrip(), "title": match.group(2), "lines": []}
                current = number
                continue
        if current is None:
            preamble.append(line)
        else:
            sections[current]["lines"].append(line)
    style = "hash" if heading_mode or not sections else "bold"
    return {"preamble": preamble, "sections": sections, "style": style}


def default_heading(number, style="hash"):
    name = SECTION_NAMES[number]
    return f"**{number}. {name}**" if style == "bold" else f"## {number}. {name}"


def is_narrative_layout(parsed):
    """True when the previous PCOS_NOW uses the v3 narrative section titles."""
    for number, markers in NARRATIVE_TITLES.items():
        section = parsed["sections"].get(number)
        if section and any(marker in unescape_md(section["title"]).lower() for marker in markers):
            return True
    return False


def section_body(parsed, number):
    section = parsed["sections"].get(number)
    return "\n".join(section["lines"]).strip("\n") if section else ""


# ------------------------------------------------------------- helpers --

def recon_items(recon, key):
    section = (recon.get("sections") or {}).get(key) or {}
    return [item for item in section.get("items", [])
            if item.get("level", 0) == 0 and normalize_title(item.get("text", ""))]


def _already_present(text, existing_norms):
    norm = normalize_title(text)
    return bool(norm) and any(norm == known or norm in known for known in existing_norms if known)


def _append_block(body, new_lines):
    if not new_lines:
        return body
    return (body + "\n" if body else "") + "\n".join(new_lines)


BAD_DATE_MARK = "[BAD DATE]"


def _age_text(today, value):
    """Age in days, or a visible mark when Updated is empty or not YYYY-MM-DD."""
    age = age_days(today, value)
    return BAD_DATE_MARK if age is None else str(age)


def _work_rows(rows):
    """Rows outside Room PERSONAL (sections 2, 3 and 6 never show PERSONAL)."""
    return [row for row in rows if row["Room"] != PERSONAL_ROOM]


def _low_rank(vocab):
    order = vocab.priority_order
    return order.index("LOW") if "LOW" in order else max(len(order) - 1, 0)


def active_sort_key(row, vocab):
    """Priority rank; Active-Low rows always take LOW rank, after other LOW rows."""
    is_active_low = row["Status"] == ACTIVE_LOW_STATUS
    rank = _low_rank(vocab) if is_active_low else vocab.priority_rank(row["Priority"])
    return (rank, is_active_low, room_sort_key(row["Room"]), row["Task ID"])


# ------------------------------------------------------------ sections --

def append_decisions(body, recon, today):
    items = recon_items(recon, "action_on_joe")
    existing = [normalize_title(line) for line in body.splitlines()]
    numbers = [int(match.group(1)) for line in body.splitlines()
               if (match := NUMBERED_ITEM_RE.match(line))]
    next_number = max(numbers, default=0) + 1
    tag = f"[NEW from RECON {recon.get('as_of') or today.isoformat()}]"
    added = []
    for item in items:
        if _already_present(item["text"], existing):
            continue
        added.append(f"{next_number}. {tag} {item['text']}")
        next_number += 1
    return _append_block(body, added)


def append_candidates(body, recon):
    items = recon_items(recon, "patterns")
    existing = [normalize_title(line) for line in body.splitlines()]
    added = [f"- [CANDIDATE from RECON] {item['text']}" for item in items
             if not _already_present(item["text"], existing)]
    return _append_block(body, added)


def active_table(rows, today, vocab=None):
    vocab = vocab or get_vocab()
    selected = [row for row in _work_rows(rows) if row["Status"] in ACTIVE_STATUSES]
    selected.sort(key=lambda row: active_sort_key(row, vocab))
    if not selected:
        return "_No active rows._"
    return md_table(
        ["Task ID", "Title", "Room", "Status", "Priority", "Owner", "Next Action", "Updated", "Age (d)"],
        [[row["Task ID"], row["Title"], row["Room"], row["Status"], row["Priority"], row["Owner"],
          row["Next Action"], row["Updated"], _age_text(today, row["Updated"])] for row in selected],
    )


def waiting_table(rows, recon, today, aged_days=None, vocab=None):
    if aged_days is None:
        aged_days = (vocab or get_vocab()).aged_days
    waiting_rows = [row for row in _work_rows(rows) if row["Status"] == WAITING_STATUS]
    waiting_ids = {row["Task ID"] for row in waiting_rows}
    personal_ids = {row["Task ID"] for row in rows if row["Room"] == PERSONAL_ROOM}
    referenced, extra = set(), []
    for item in recon_items(recon, "waiting_on_others"):
        task_ids = item.get("task_ids", [])
        hits = [task_id for task_id in task_ids if task_id in waiting_ids]
        if hits:
            referenced.update(hits)  # the work rows named get [RECON]; the line itself is not repeated
        elif any(task_id in personal_ids for task_id in task_ids):
            continue  # a RECON line only about PERSONAL tasks never enters section 3
        else:
            extra.append(item)

    entries = []
    for row in waiting_rows:
        age = age_days(today, row["Updated"])
        flags = []
        if age is not None and age >= aged_days:
            flags.append("[AGED]")
        if row["Task ID"] in referenced:
            flags.append("[RECON]")
        entries.append((age, [row["Task ID"], row["Title"], row["Waiting On"], row["Updated"],
                              "" if age is None else str(age), " ".join(flags), "Worklist"]))
    for item in extra:
        isos = [found["iso"] for found in item.get("dates", []) if found.get("iso")]
        since = min(isos) if isos else ""
        age = age_days(today, since) if since else None
        who = item["people"][0]["name"] if item.get("people") else ""
        flag = "[AGED]" if age is not None and age >= aged_days else ""
        entries.append((age, ["", item["text"], who, since, "" if age is None else str(age), flag, "RECON s3"]))

    if not entries:
        return "_Nothing waiting._"
    entries.sort(key=lambda entry: (entry[0] is None, -(entry[0] or 0), entry[1][0]))
    return md_table(["Task ID", "Title / item", "Waiting On", "Since", "Age (d)", "Flag", "Source"],
                    [cells for _, cells in entries])


def stale_list(rows, today, stale_days=None, vocab=None):
    vocab = vocab or get_vocab()
    if stale_days is None:
        stale_days = vocab.stale_days
    selected = [row for row in _work_rows(rows) if row["Status"] == STALE_STATUS]
    selected.sort(key=lambda row: (parse_date(row["Updated"]) or date.max, row["Task ID"]))
    if not selected:
        return "_No Stale-Triage rows._"
    lines = []
    for row in selected:
        age = age_days(today, row["Updated"])
        mark = " [ARCHIVE?]" if age is not None and age >= stale_days else ""
        age_text = f"{age} d" if age is not None else "age unknown"
        lines.append(f"- {row['Task ID']} - {row['Title']} (Room {row['Room']}, "
                     f"updated {row['Updated'] or '?'}, {age_text}){mark}")
    return "\n".join(lines)


# --------------------------------------------------------------- build --

def build_now(rows, recon, prev_text, today, aged_days=None, stale_days=None, vocab=None, carry_all=False):
    """Return (draft_markdown, warnings).

    Legacy layout: section 0 is carried through unchanged when the previous
    file has it and is never created. Sections 2, 3, 6 are regenerated; 1 and 5
    are carried and appended from the RECON; 4, 7, 8 are carried unchanged.
    Missing sections 1 to 8 get a default heading in the previous file's style.
    ``aged_days`` and ``stale_days`` default to the vocabulary's values.

    Narrative layout (v3 titles, see NARRATIVE_TITLES) or ``carry_all``: every
    section is carried unchanged and nothing is appended; use now_check for the
    Worklist cross-check.
    """
    vocab = vocab or get_vocab()
    if aged_days is None:
        aged_days = vocab.aged_days
    if stale_days is None:
        stale_days = vocab.stale_days
    prev = parse_now(prev_text)
    warnings = []
    if carry_all or is_narrative_layout(prev):
        reason = "--carry-all" if carry_all else "narrative (v3) section titles"
        warnings.append(f"{reason}: every section carried unchanged, nothing regenerated or appended; "
                        "run now_check for the Worklist cross-check")
        # The previous text is copied exactly (order, line endings, trailing blanks),
        # minus any earlier generator marker, under one new marker line.
        newline = "\r\n" if "\r\n" in prev_text else "\n"
        kept = [line for line in prev_text.splitlines(keepends=True) if not line.startswith(GENERATOR_MARK)]
        marker = (f"{GENERATOR_MARK} v{__version__} on {today.isoformat()}: {reason}; all sections carried "
                  "unchanged. Review before applying. -->")
        return marker + newline + "".join(kept), warnings
    out = [f"{GENERATOR_MARK} v{__version__} on {today.isoformat()}: sections 2, 3, 6 regenerated; "
           "1 and 5 appended from RECON; 0, 4, 7, 8 carried unchanged. Review before applying. -->"]
    preamble = [line for line in prev["preamble"] if not line.startswith(GENERATOR_MARK)]
    preamble_text = "\n".join(preamble).strip("\n")
    if preamble_text:
        out += [preamble_text, ""]
    else:
        out.append("")

    if 0 in prev["sections"]:
        out += [prev["sections"][0]["heading"], ""]
        body = section_body(prev, 0)
        if body:
            out += [body, ""]

    for number in range(1, 9):
        section = prev["sections"].get(number)
        heading = section["heading"] if section else default_heading(number, prev["style"])
        body = section_body(prev, number)
        if not section:
            warnings.append(f"section {number} missing in previous PCOS_NOW; default heading used")
        if number == 1:
            body = append_decisions(body, recon, today)
        elif number == 2:
            body = active_table(rows, today, vocab)
        elif number == 3:
            body = waiting_table(rows, recon, today, aged_days, vocab)
        elif number == 5:
            body = append_candidates(body, recon)
        elif number == 6:
            body = stale_list(rows, today, stale_days, vocab)
        out += [heading, ""]
        if body:
            out += [body, ""]
    return "\n".join(out).rstrip("\n") + "\n", warnings


def now_build_command(args):
    today = args.today or date.today()
    vocab = get_vocab(args.vocab)
    rows = read_worklist(args.csv, use_pandas=args.pandas)
    recon = load_recon(args.recon, known_people=split_people(args.people))
    prev_path = Path(args.prev)
    prev_text = read_text_file(prev_path, "previous PCOS_NOW")
    draft, warnings = build_now(rows, recon, prev_text, today, aged_days=args.aged_days,
                                stale_days=args.stale_days, vocab=vocab,
                                carry_all=getattr(args, "carry_all", False))
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / DRAFT_NAME
    for source in (Path(args.csv), Path(args.recon), prev_path):
        if source.exists() and out_path.resolve() == source.resolve():
            raise WorklistError(f"refusing to overwrite an input file: {source}; choose another --out-dir")
    out_path.write_text(draft, encoding="utf-8", newline="\n")
    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)
    carried = any("carried unchanged" in warning for warning in warnings)
    summary = "all sections carried" if carried else "2, 3, 6 regenerated; 1, 5 appended; 0, 4, 7, 8 carried"
    print(f"now_build: wrote {out_path} ({summary})")
    return 0
